/**
 * tests-data.js
 * Pre-loaded official College Board Digital SAT Practice Tests.
 */

window.OFFICIAL_TESTS = {
  pt4: {
    testId: 'pt4',
    title: 'Practice Test #4',
    source: 'College Board Digital SAT Practice Test #4',
    available: true,
    modules: { rw: true, math: false },
    sections: {
      RW: {
        module1: [
          { id: 'pt4-rw1-q1', number: 1, text: "The spacecraft OSIRIS-REx briefly made contact with the asteroid 101955 Bennu in 2020. NASA scientist Daniella DellaGiustina reports that despite facing the unexpected obstacle of a surface mostly covered in boulders, OSIRIS-REx successfully _______ a sample of the surface, gathering pieces of it to bring back to Earth.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['attached', 'collected', 'followed', 'replaced'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt4-rw1-q2', number: 2, text: "Research conducted by planetary scientist Katarina Miljkovic suggests that the Moon's surface may not accurately _______ early impact events. When the Moon was still forming, its surface was softer, and asteroid or meteoroid impacts would have left less of an impression; thus, evidence of early impacts may no longer be present.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['reflect', 'receive', 'evaluate', 'mimic'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt4-rw1-q3', number: 3, text: "Handedness, a preferential use of either the right or left hand, typically is easy to observe in humans. Because this trait is present but less _______ in many other animals, animal-behavior researchers often employ tasks specially designed to reveal individual animals' preferences for a certain hand or paw.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['recognizable', 'intriguing', 'significant', 'useful'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt4-rw1-q4', number: 4, text: "It is by no means _______ to recognize the influence of Dutch painter Hieronymus Bosch on Ali Banisadr's paintings; indeed, Banisadr himself cites Bosch as an inspiration. However, some scholars have suggested that the ancient Mesopotamian poem Epic of Gilgamesh may have had a far greater impact on Banisadr's work.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['substantial', 'satisfying', 'unimportant', 'appropriate'], correctAnswer: 2, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt4-rw1-q5', number: 5, text: 'Which choice best states the main purpose of the text?', options: ["To reveal the shop owner's conflicted feelings about the new picture", "To convey the shop owner's resentment of the person he got the new picture from", 'To describe the items that the shop owner most highly prizes', 'To explain differences between the new picture and other pictures in the shop'], correctAnswer: 0, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is adapted from Susan Glaspell's 1912 short story \"Out There.\" An elderly shop owner is looking at a picture that he recently acquired and hopes to sell.\n\nIt did seem that the picture failed to fit in with the rest of the shop. A persuasive young fellow who claimed he was closing out his stock let the old man have it for what he called a song. It was only a little out-of-the-way store which subsisted chiefly on the framing of pictures. The old man looked around at his views of the city, his pictures of cats and dogs, his flaming bits of landscape. \"Don't belong in here,\" he fumed.\n\nAnd yet the old man was secretly proud of his acquisition. There was a hidden dignity in his scowling as he shuffled about pondering the least ridiculous place for the picture." },
          { id: 'pt4-rw1-q6', number: 6, text: 'Which choice best describes the overall structure of the text?', options: ['The speaker assesses a natural phenomenon, then questions the accuracy of her assessment.', 'The speaker describes a distinctive sight in nature, then ponders what meaning to attribute to that sight.', 'The speaker presents an outdoor scene, then considers a human behavior occurring within that scene.', 'The speaker examines her surroundings, then speculates about their influence on her emotional state.'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "The following text is from the 1923 poem \"Black Finger\" by Angelina Weld Grimké.\n\nI have just seen a most beautiful thing,\nSlim and still,\nAgainst a gold, gold sky,\nA straight black cypress,\nSensitive,\nExquisite,\nA black finger\nPointing upwards.\nWhy, beautiful still finger, are you black?\nAnd why are you pointing upwards?" },
          { id: 'pt4-rw1-q7', number: 7, text: 'Which choice best describes the overall structure of the text?', options: ['The speaker questions an increasingly prevalent attitude, then summarizes his worldview.', 'The speaker regrets his isolation from others, then predicts a profound change in society.', 'The speaker concedes his personal shortcomings, then boasts of his many achievements.', 'The speaker addresses a criticism leveled against him, then announces a grand ambition of his.'], correctAnswer: 3, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "The following text is from Walt Whitman's 1860 poem \"Calamus 24.\"\n\nI HEAR it is charged against me that I seek to destroy institutions;\nBut really I am neither for nor against institutions\n(What indeed have I in common with them?—\nOr what with the destruction of them?),\nOnly I will establish in the Mannahatta [Manhattan] and in every city of These States, inland and seaboard,\nAnd in the fields and woods, and above every keel [ship] little or large, that dents the water,\nWithout edifices, or rules, or trustees, or any argument,\nThe institution of the dear love of comrades." },
          { id: 'pt4-rw1-q8', number: 8, text: 'Which choice best describes the function of the third sentence in the overall structure of the text?', options: ['It states the hypothesis that Chang and colleagues had set out to investigate using mimosa trees and B. terrenus.', 'It presents a generalization that is exemplified by the discussion of the mimosa trees and B. terrenus.', 'It offers an alternative explanation for the findings of Chang and colleagues.', 'It provides context that clarifies why the species mentioned spread to new locations.'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: 'The mimosa tree evolved in East Asia, where the beetle Bruchidius terrenus preys on its seeds. In 1785, mimosa trees were introduced to North America, far from any B. terrenus. But evolutionary links between predators and their prey can persist across centuries and continents. Around 2001, B. terrenus was introduced in southeastern North America near where botanist Shu-Mei Chang and colleagues had been monitoring mimosa trees. Within a year, 93 percent of the trees had been attacked by the beetles.' },
          { id: 'pt4-rw1-q9', number: 9, text: 'Based on the texts, how would Graeber and Wengrow (Text 2) most likely respond to the "conventional wisdom" presented in Text 1?', options: ['By conceding the importance of hierarchical systems but asserting the greater significance of decentralized collective societies', 'By disputing the idea that developments in social structures have followed a linear progression through distinct stages', "By acknowledging that hierarchical roles likely weren't a part of social systems before the rise of agriculture", 'By challenging the assumption that groupings of hunter-gatherers were among the earliest forms of social structure'], correctAnswer: 1, type: 'MCQ', domain: 'Information and Ideas', tag: 'Cross-Text Connections', passage: "Text 1\nConventional wisdom long held that human social systems evolved in stages, beginning with hunter-gatherers forming small bands of members with roughly equal status. The shift to agriculture about 12,000 years ago sparked population growth that led to the emergence of groups with hierarchical structures: associations of clans first, then chiefdoms, and finally, bureaucratic states.\n\nText 2\nIn a 2021 book, anthropologist David Graeber and archaeologist David Wengrow maintain that humans have always been socially flexible, alternately forming systems based on hierarchy and collective ones with decentralized leadership. The authors point to evidence that as far back as 50,000 years ago some hunter-gatherers adjusted their social structures seasonally, at times dispersing in small groups but also assembling into communities that included esteemed individuals." },
          { id: 'pt4-rw1-q10', number: 10, text: 'Which choice best states the main idea of the text?', options: ['Mary hides in the garden to avoid doing her chores.', 'Mary is getting bored with pulling up so many weeds in the garden.', 'Mary is clearing out the garden to create a space to play.', "Mary feels very satisfied when she's taking care of the garden."], correctAnswer: 3, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is adapted from Frances Hodgson Burnett's 1911 novel The Secret Garden.\n\nMary was an odd, determined little person, and now she had something interesting to be determined about, she was very much absorbed, indeed. She worked and dug and pulled up weeds steadily, only becoming more pleased with her work every hour instead of tiring of it. It seemed to her like a fascinating sort of play." },
          { id: 'pt4-rw1-q11', number: 11, text: 'Based on the text, in what way is the human mind like a flower?', options: ['It becomes increasingly vigorous with the passage of time.', 'It draws strength from changes in the weather.', 'It requires proper nourishment in order to thrive.', 'It perseveres despite challenging circumstances.'], correctAnswer: 2, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is from Ezra Pound's 1909 poem \"Hymn III.\"\n\nAs a fragile and lovely flower unfolds its gleaming foliage on the breast of the fostering earth, if the dew and the rain draw it forth;\nSo doth my tender mind flourish, if it be fed with the sweet dew of the fostering spirit,\nLacking this, it beginneth straightway to languish, even as a floweret born upon dry earth, if the dew and the rain tend it not." },
          { id: 'pt4-rw1-q12', number: 12, text: 'Which choice best states the main idea of the text?', options: ['Buck has become less social since he began living with Thornton.', 'Buck mistrusts humans and does his best to avoid them.', "Buck has been especially well liked by most of Thornton's friends.", 'Buck holds Thornton in higher regard than any other person.'], correctAnswer: 3, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is adapted from Jack London's 1903 novel The Call of the Wild.\n\nThornton alone held [Buck]. The rest of mankind was as nothing. Chance travellers might praise or pet him; but he was cold under it all, and from a too demonstrative man he would get up and walk away. When Thornton's partners, Hans and Pete, arrived on the long-expected raft, Buck refused to notice them till he learned they were close to Thornton; after that he tolerated them in a passive sort of way, accepting favors from them as though he favored them by accepting." }
        ],
        module2Easy: [], module2Hard: []
      },
      MATH: { module1: [], module2Easy: [], module2Hard: [] }
    },
    usedRealAnswers: true,
    extractionNote: 'Practice Test #4 — RW Module 1 (12 questions)'
  },

  pt5: {
    testId: 'pt5',
    title: 'Practice Test #5',
    source: 'College Board Digital SAT Practice Test #5',
    available: true,
    modules: { rw: true, math: false },
    sections: {
      RW: {
        module1: [
          { id: 'pt5-rw1-q1', number: 1, text: 'As used in the text, what does the word "trace" most nearly mean?', options: ['Evidence', 'Blemish', 'Amount', 'Sketch'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: "The following text is from the 1913 story \"The King's Coin\" by Emily Pauline Johnson.\n\nAt supper time, Fox-Foot would allow no fire to be built, no landing to be made, no trace of their passing to be left. They ate canned meat and marmalade, drank again of the stream and pushed on, until just at dusk they reached the edge of a long, still lake, with shores of granite and dense fir forest." },
          { id: 'pt5-rw1-q2', number: 2, text: "Many ancient sculptures of people's heads are missing their noses. This is because the nose is the most _______ part of a sculpture of a person's head. It is delicate and sticks out from the rest of the sculpture, making it especially easy to break.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['recognizable', 'fragile', 'common', 'sophisticated'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt5-rw1-q3', number: 3, text: "K.D. Leka and colleagues found that the Sun's corona provides an advance indication of solar flares. Preceding a flare, the corona temporarily exhibits increased brightness above the region where the flare is _______.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['antecedent', 'impending', 'innocuous', 'perpetual'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt5-rw1-q4', number: 4, text: "To demonstrate that the integrity of underground metal pipes can be assessed without unearthing the pipes, engineer Aroba Saleem and colleagues _______ the tendency of some metals' internal magnetic fields to alter under stress.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['hypothesized', 'discounted', 'redefined', 'exploited'], correctAnswer: 3, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt5-rw1-q5', number: 5, text: "Despite the generalizations about human behavior they have produced, many studies of behavioral psychology have used highly unrepresentative subject pools. To _______ this situation, it is necessary to actively recruit subjects from diverse backgrounds and locations.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['sanction', 'ameliorate', 'rationalize', 'postulate'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt5-rw1-q6', number: 6, text: 'Which choice best states the main purpose of the text?', options: ['To compare basketball with other sports', 'To provide details of how to play basketball', 'To state how players will be chosen for the basketball team', 'To explain why the narrator thinks she might make the basketball team'], correctAnswer: 3, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is adapted from Jean Webster's 1912 novel Daddy-Long-Legs.\n\n[The college is] organizing the Freshman basket-ball team and there's just a chance that I shall make it. I'm little of course, but terribly quick and wiry and tough. While the others are hopping about in the air, I can dodge under their feet and grab the ball." },
          { id: 'pt5-rw1-q7', number: 7, text: 'Which choice best states the main purpose of the text?', options: ['To compare Spanish-language newspapers published in Texas today with ones published there during the late 1800s', 'To explain that Spanish-language newspapers thrived in Texas and especially in El Paso during the late 1800s', 'To argue that Spanish-language newspapers published in El Paso influenced the ones published in San Antonio during the late 1800s', 'To explain why Spanish-language newspapers published in Texas were so popular in Mexico during the late 1800s'], correctAnswer: 1, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: 'In the late 1800s, Spanish-language newspapers flourished in cities across Texas. San Antonio alone produced eleven newspapers in Spanish between 1890 and 1900. But El Paso surpassed all other cities in the state. This city produced twenty-two newspapers in Spanish during that period. El Paso is located on the border with Mexico and has always had a large population of Spanish speakers. Thus, it is unsurprising that this city became such a rich site for Spanish-language journalism.' },
          { id: 'pt5-rw1-q8', number: 8, text: 'Which choice best describes the function of the underlined sentence in the text as a whole?', options: ['To contrast the conditions in the Atacama Desert with those on Mars', 'To explain why many life-forms cannot survive in the Atacama Desert', 'To indicate why astrobiologists choose to conduct research in the Atacama Desert', 'To describe certain limitations to conducting scientific study in the Atacama Desert'], correctAnswer: 2, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "Chile's Atacama Desert is one of the driest places on Earth. Mary Beth Wilhelm and other astrobiologists search for life, or its remains, in this harsh place because the desert closely mirrors the extreme environment on Mars. The algae and bacteria found in Atacama's driest regions may offer clues about Martian life." },
          { id: 'pt5-rw1-q9', number: 9, text: 'Which choice best describes the function of the underlined portion in the text as a whole?', options: ['It presents an objection to the argument of Guerra et al. about transportation mode choice in urban areas of Mexico.', 'It explains why it is challenging to influence transit ridership solely by altering characteristics of a transit system.', 'It illustrates the claim that a characteristic associated with high transit ridership in Mexico City is not associated with high transit ridership elsewhere.', 'It substantiates the assertion that population density, the spatial distribution of jobs, and demographic characteristics are important factors in transportation mode choice.'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "More than 60% of journeys in Mexico City occur via public transit, but simply reproducing a feature of the city's transit system is unlikely to induce a significant increase in another city's transit ridership. System features do affect ridership, of course, but there is an irreducibly contextual dimension of transportation mode choice." },
          { id: 'pt5-rw1-q10', number: 10, text: 'Which choice best describes the overall structure of the text?', options: ["It describes a phenomenon that scientists do not fully understand, explains a research team's hypothesis about that phenomenon, and then describes a finding that led the team to refine the hypothesis.", "It introduces an unresolved scientific question, presents a research team's hypothesis pertaining to that question, and then describes an observation made by the team that conflicts with that hypothesis.", 'It discusses a process that scientists are somewhat unclear about, introduces competing hypotheses about that process, and then explains how a research team concluded that one of those hypotheses is likely correct.', 'It explains a hypothesis that has been the subject of scientific debate, discusses how a research team tested that hypothesis, and then presents data the team collected that validate the hypothesis.'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: 'Changes to vegetation cover and other human activities influence carbon and nitrogen levels in soil, though how deep these effects extend is unclear. Hypothesizing that differences in land use lead to differences in carbon and nitrogen levels that are not restricted to the topsoil layer (0–30 cm deep), Chukwuebuka Okolo and colleagues sampled soils across multiple land-use types. They found, though, that across land-use types, carbon and nitrogen decreased to comparably low levels beyond depths of 30 cm.' },
          { id: 'pt5-rw1-q11', number: 11, text: "According to the text, what was surprising to scientists studying the seismic activity data from NASA's InSight lander?", options: ['The surface temperature of Mars has been rising.', 'There were different types of seismic waves causing marsquakes.', "NASA's InSight lander collected less data than scientists had expected.", 'All the marsquakes started from the same location on the planet.'], correctAnswer: 3, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "Recently, scientists looked at data collected by NASA's InSight lander to learn more about seismic activity on Mars, known as marsquakes. The data show that the marsquakes all started from the same location on the planet. This discovery was surprising to scientists, as they expected that the marsquakes would originate from all over the planet." },
          { id: 'pt5-rw1-q12', number: 12, text: 'According to the text, what do some historians suggest about Maya civilization?', options: ['Maya civilization acquired the use of zero from the Olmec civilization.', 'Maya civilization respected its historians more than it respected its mathematicians.', 'Maya civilization was highly secretive about its intellectual achievements.', 'Maya civilization tried to introduce its writing system to other civilizations.'], correctAnswer: 0, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: 'The ancient writing system used in the Maya kingdoms of southern Mexico and Central America had a symbol for the number zero. The earliest known example of the symbol dates to more than 2,000 years ago. Some historians suggest that Maya mathematicians inherited it from the Olmec civilization, which flourished in the region 2,400–3,600 years ago.' }
        ],
        module2Easy: [], module2Hard: []
      },
      MATH: { module1: [], module2Easy: [], module2Hard: [] }
    },
    usedRealAnswers: true,
    extractionNote: 'Practice Test #5 — RW Module 1 (12 questions)'
  },

  pt6: {
    testId: 'pt6',
    title: 'Practice Test #6',
    source: 'College Board Digital SAT Practice Test #6',
    available: true,
    modules: { rw: true, math: false },
    sections: {
      RW: {
        module1: [
          { id: 'pt6-rw1-q1', number: 1, text: "Though not closely related, the hedgehog tenrecs of Madagascar share basic _______ true hedgehogs, including protective spines, pointed snouts, and small body size.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['examples of', 'concerns about', 'indications of', 'similarities with'], correctAnswer: 3, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt6-rw1-q2', number: 2, text: "In editor Lisa Yaszek's introduction to her anthology The Future Is Female!, Yaszek identifies an increasing sense of _______ feminist mode of writing in the 1970s.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['a prudently', 'an overtly', 'a cordially', 'an inadvertently'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt6-rw1-q3', number: 3, text: "_______ the long-standing trend of overemphasizing teenagers and young adults in research on social media use, scholars have recently begun to expand their focus to include senior citizens.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['Exacerbating', 'Redressing', 'Epitomizing', 'Precluding'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt6-rw1-q4', number: 4, text: 'As used in the text, what does the word "disputing" most nearly mean?', options: ['Arguing about', 'Disapproving of', 'Asserting possession of', 'Providing resistance to'], correctAnswer: 3, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: "The following text is adapted from James Baldwin's 1956 novel Giovanni's Room.\n\nThe multitude of Paris seems to be dressed in blue every day but Sunday. Here they were now, in blue, disputing every inch, our passage, with their wagons, handtrucks, their bursting baskets." },
          { id: 'pt6-rw1-q5', number: 5, text: "While recent scholarship has undermined claims that the works of twelfth-century Islamic philosopher Ibn Rushd were _______ other Muslim philosophers of his time, it is indisputable that his location in Spain meant that his works were primarily available thousands of miles west of the era's center of Islamic thought.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['controversial among', 'antagonistic toward', 'imitated by', 'inconsequential to'], correctAnswer: 3, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt6-rw1-q6', number: 6, text: 'Which choice best describes the function of the underlined sentence in the text as a whole?', options: ["It elaborates on the previous sentence's statement about a transitional moment in Johnson's artistic career.", "It provides information about Johnson's travels in support of a claim about his artistic influences.", "It recounts a moment in Johnson's personal life that enabled the success of his subsequent career.", "It presents evidence that calls into question the previous sentence's characterization of Johnson's artistic development."], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "On painter William H. Johnson's return to the United States in 1938 after a decade in Europe, his style underwent an abrupt transformation. Turning away from landscapes painted in an expressionist style, Johnson began painting portraits of Black Americans in a bold new way." },
          { id: 'pt6-rw1-q7', number: 7, text: 'Which choice best states the main purpose of the text?', options: ['To provide details about how Argerich identifies which pieces of music she will perform', "To assert that Argerich's performances look effortless because of how she prepares for them", 'To discuss the kinds of music Argerich feels most comfortable encountering for the first time', "To describe the unique way that Argerich approaches music she hasn't performed before"], correctAnswer: 1, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "When classical pianist Martha Argerich performs, it appears as if the music is coming to her spontaneously. Her apparent ease, however, is due to a tremendous amount of preparation. Despite Argerich's experience and virtuosity, she never takes for granted that she knows a piece of music." }
        ],
        module2Easy: [], module2Hard: []
      },
      MATH: { module1: [], module2Easy: [], module2Hard: [] }
    },
    usedRealAnswers: true,
    extractionNote: 'Practice Test #6 — RW Module 1 (7 questions)'
  },

  pt7: {
    testId: 'pt7',
    title: 'Practice Test #7',
    source: 'College Board Digital SAT Practice Test #7',
    available: true,
    modules: { rw: true, math: false },
    sections: {
      RW: {
        module1: [
          { id: 'pt7-rw1-q1', number: 1, text: "On the basis of extensive calculations and models, astronomers in the 1990s predicted that the collision of two neutron stars or a neutron star and a black hole could release a massive burst of gamma rays in an event called a kilonova. This _______ was confirmed with observations in 2017.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['theory', 'evidence', 'constant', 'experiment'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt7-rw1-q2', number: 2, text: 'As used in the text, what does the word "clear" most nearly mean?', options: ['Simple', 'Understandable', 'Obvious', 'Transparent'], correctAnswer: 3, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: "The following text is from John Muir's 1913 autobiography The Story of My Boyhood and Youth.\n\nThe water was so clear that it was almost invisible, and when we floated slowly out over the plants and fishes, we seemed to be miraculously sustained in the air while exploring a veritable fairyland." },
          { id: 'pt7-rw1-q3', number: 3, text: "At the turn of the twentieth century, Black residents of Richmond, Virginia, had few formal options for banking and other financial services. To _______ this situation, Maggie Lena Walker chartered the St. Luke Penny Savings Bank in 1903.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['prolong', 'rectify', 'retain', 'highlight'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt7-rw1-q4', number: 4, text: "The results of randomized clinical trials testing the efficacy of common medical interventions sometimes fail to _______ conclusions that practitioners reach based on their real-world observations of patients.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['circumvent', 'corroborate', 'disseminate', 'implement'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt7-rw1-q5', number: 5, text: "Diadromous fish migrate between freshwater and marine biomes during their life cycle. The migration's obligate nature is why diadromous fish can be _______ those that are merely euryhaline (able to tolerate high salinity).\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['demarcated from', 'reconstituted as', 'conflated with', 'derived from'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
          { id: 'pt7-rw1-q6', number: 6, text: 'Which choice best describes the function of the underlined portion in the text as a whole?', options: ['It illustrates that a fire provides comfort beyond physical warmth.', 'It summarizes the information that came before it in the text.', 'It explains that the house remains cold even in summer.', 'It suggests that the author feels comfortable in her home with or without a fire.'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "The following text is from Joan Didion's memoir The Year of Magical Thinking.\n\n[I]n California we heated our houses by building fires. We built fires even on summer evenings, because the fog came in. Fires said we were home, we had drawn the circle, we were safe through the night." }
        ],
        module2Easy: [], module2Hard: []
      },
      MATH: { module1: [], module2Easy: [], module2Hard: [] }
    },
    usedRealAnswers: true,
    extractionNote: 'Practice Test #7 — RW Module 1 (6 questions)'
  },

  pt9: { testId: 'pt9', title: 'Practice Test #9', available: false, modules: { rw: false, math: false } },
  pt10: { testId: 'pt10', title: 'Practice Test #10', available: false, modules: { rw: false, math: false } }
};

window.SAT_TIPS = [
  { title: 'Words in Context', tip: 'Read the full sentence, plug each choice into the blank, and pick the one that keeps the meaning precise and logical. Eliminate options that are too extreme or change the tone.' },
  { title: 'Command of Evidence', tip: 'The correct answer must be directly supported by the passage. If you cannot point to a specific line or phrase that backs the choice, it is wrong.' },
  { title: 'Cross-Text Connections', tip: 'Identify the main claim of each text first. Then ask how Text 2 would respond to Text 1 — agree, disagree, qualify, or expand.' },
  { title: 'Math — Heart of Algebra', tip: 'Isolate the variable systematically. When stuck, plug the answer choices back into the original equation (back-solving).' },
  { title: 'Math — Problem Solving & Data', tip: 'Read the graph or table title and axes carefully before looking at the question. Units and scales are common traps.' },
  { title: 'Timing Strategy', tip: 'On RW modules aim for ~1 minute per question. Flag hard ones and move on — come back only if time remains.' },
  { title: 'Student-Produced Response (SPR)', tip: 'Enter fractions as simplified form (e.g. 3/4). Do not enter mixed numbers. The grid accepts decimals and negatives where appropriate.' },
  { title: 'Bluebook Mindset', tip: 'Treat every practice test like the real thing: same timing, same flagging, same review at the end. Consistency builds stamina.' }
];
