/**
 * tests-data.js
 * Pre-loaded official College Board Digital SAT Practice Tests.
 */

window.OFFICIAL_TESTS = {
  pt4: {
    testId: 'pt4', title: 'Practice Test #4', source: 'College Board Digital SAT Practice Test #4',
    available: true, modules: { rw: true, math: false },
    sections: { RW: { module1: [
      { id: 'pt4-rw1-q1', number: 1, text: "The spacecraft OSIRIS-REx briefly made contact with the asteroid 101955 Bennu in 2020. NASA scientist Daniella DellaGiustina reports that despite facing the unexpected obstacle of a surface mostly covered in boulders, OSIRIS-REx successfully _______ a sample of the surface, gathering pieces of it to bring back to Earth.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['attached', 'collected', 'followed', 'replaced'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
      { id: 'pt4-rw1-q2', number: 2, text: "Research conducted by planetary scientist Katarina Miljkovic suggests that the Moon's surface may not accurately _______ early impact events. When the Moon was still forming, its surface was softer, and asteroid or meteoroid impacts would have left less of an impression; thus, evidence of early impacts may no longer be present.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['reflect', 'receive', 'evaluate', 'mimic'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
      { id: 'pt4-rw1-q3', number: 3, text: "Handedness, a preferential use of either the right or left hand, typically is easy to observe in humans. Because this trait is present but less _______ in many other animals, animal-behavior researchers often employ tasks specially designed to reveal individual animals' preferences for a certain hand or paw.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['recognizable', 'intriguing', 'significant', 'useful'], correctAnswer: 0, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
      { id: 'pt4-rw1-q4', number: 4, text: "It is by no means _______ to recognize the influence of Dutch painter Hieronymus Bosch on Ali Banisadr's paintings; indeed, Banisadr himself cites Bosch as an inspiration. However, some scholars have suggested that the ancient Mesopotamian poem Epic of Gilgamesh may have had a far greater impact on Banisadr's work.\n\nWhich choice completes the text with the most logical and precise word or phrase?", options: ['substantial', 'satisfying', 'unimportant', 'appropriate'], correctAnswer: 2, type: 'MCQ', domain: 'Craft and Structure', tag: 'Words in Context', passage: null },
      { id: 'pt4-rw1-q5', number: 5, text: 'Which choice best states the main purpose of the text?', options: ["To reveal the shop owner's conflicted feelings about the new picture", "To convey the shop owner's resentment of the person he got the new picture from", 'To describe the items that the shop owner most highly prizes', 'To explain differences between the new picture and other pictures in the shop'], correctAnswer: 0, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is adapted from Susan Glaspell's 1912 short story \"Out There.\" An elderly shop owner is looking at a picture that he recently acquired and hopes to sell.\n\nIt did seem that the picture failed to fit in with the rest of the shop. A persuasive young fellow who claimed he was closing out his stock let the old man have it for what he called a song. The old man looked around at his views of the city, his pictures of cats and dogs, his flaming bits of landscape. \"Don't belong in here,\" he fumed. And yet the old man was secretly proud of his acquisition." },
      { id: 'pt4-rw1-q6', number: 6, text: 'Which choice best describes the overall structure of the text?', options: ['The speaker assesses a natural phenomenon, then questions the accuracy of her assessment.', 'The speaker describes a distinctive sight in nature, then ponders what meaning to attribute to that sight.', 'The speaker presents an outdoor scene, then considers a human behavior occurring within that scene.', 'The speaker examines her surroundings, then speculates about their influence on her emotional state.'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "The following text is from the 1923 poem \"Black Finger\" by Angelina Weld Grimké.\n\nI have just seen a most beautiful thing,\nSlim and still,\nAgainst a gold, gold sky,\nA straight black cypress,\nSensitive,\nExquisite,\nA black finger\nPointing upwards.\nWhy, beautiful still finger, are you black?\nAnd why are you pointing upwards?" },
      { id: 'pt4-rw1-q7', number: 7, text: 'Which choice best describes the overall structure of the text?', options: ['The speaker questions an increasingly prevalent attitude, then summarizes his worldview.', 'The speaker regrets his isolation from others, then predicts a profound change in society.', 'The speaker concedes his personal shortcomings, then boasts of his many achievements.', 'The speaker addresses a criticism leveled against him, then announces a grand ambition of his.'], correctAnswer: 3, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: "The following text is from Walt Whitman's 1860 poem \"Calamus 24.\"\n\nI HEAR it is charged against me that I seek to destroy institutions;\nBut really I am neither for nor against institutions\n(What indeed have I in common with them?—\nOr what with the destruction of them?),\nOnly I will establish in the Mannahatta [Manhattan] and in every city of These States, inland and seaboard,\nAnd in the fields and woods, and above every keel [ship] little or large, that dents the water,\nWithout edifices, or rules, or trustees, or any argument,\nThe institution of the dear love of comrades." },
      { id: 'pt4-rw1-q8', number: 8, text: 'Which choice best describes the function of the third sentence in the overall structure of the text?', options: ['It states the hypothesis that Chang and colleagues had set out to investigate using mimosa trees and B. terrenus.', 'It presents a generalization that is exemplified by the discussion of the mimosa trees and B. terrenus.', 'It offers an alternative explanation for the findings of Chang and colleagues.', 'It provides context that clarifies why the species mentioned spread to new locations.'], correctAnswer: 1, type: 'MCQ', domain: 'Craft and Structure', tag: 'Text Structure and Purpose', passage: 'The mimosa tree evolved in East Asia, where the beetle Bruchidius terrenus preys on its seeds. In 1785, mimosa trees were introduced to North America, far from any B. terrenus. But evolutionary links between predators and their prey can persist across centuries and continents. Around 2001, B. terrenus was introduced in southeastern North America near where botanist Shu-Mei Chang and colleagues had been monitoring mimosa trees. Within a year, 93 percent of the trees had been attacked by the beetles.' },
      { id: 'pt4-rw1-q9', number: 9, text: 'Based on the texts, how would Graeber and Wengrow (Text 2) most likely respond to the "conventional wisdom" presented in Text 1?', options: ['By conceding the importance of hierarchical systems but asserting the greater significance of decentralized collective societies', 'By disputing the idea that developments in social structures have followed a linear progression through distinct stages', "By acknowledging that hierarchical roles likely weren't a part of social systems before the rise of agriculture", 'By challenging the assumption that groupings of hunter-gatherers were among the earliest forms of social structure'], correctAnswer: 1, type: 'MCQ', domain: 'Information and Ideas', tag: 'Cross-Text Connections', passage: "Text 1\nConventional wisdom long held that human social systems evolved in stages, beginning with hunter-gatherers forming small bands of members with roughly equal status. The shift to agriculture about 12,000 years ago sparked population growth that led to the emergence of groups with hierarchical structures.\n\nText 2\nIn a 2021 book, anthropologist David Graeber and archaeologist David Wengrow maintain that humans have always been socially flexible, alternately forming systems based on hierarchy and collective ones with decentralized leadership." },
      { id: 'pt4-rw1-q10', number: 10, text: 'Which choice best states the main idea of the text?', options: ['Mary hides in the garden to avoid doing her chores.', 'Mary is getting bored with pulling up so many weeds in the garden.', 'Mary is clearing out the garden to create a space to play.', "Mary feels very satisfied when she's taking care of the garden."], correctAnswer: 3, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is adapted from Frances Hodgson Burnett's 1911 novel The Secret Garden.\n\nMary was an odd, determined little person, and now she had something interesting to be determined about, she was very much absorbed, indeed. She worked and dug and pulled up weeds steadily, only becoming more pleased with her work every hour instead of tiring of it." },
      { id: 'pt4-rw1-q11', number: 11, text: 'Based on the text, in what way is the human mind like a flower?', options: ['It becomes increasingly vigorous with the passage of time.', 'It draws strength from changes in the weather.', 'It requires proper nourishment in order to thrive.', 'It perseveres despite challenging circumstances.'], correctAnswer: 2, type: 'MCQ', domain: 'Information and Ideas', tag: 'Central Ideas and Details', passage: "The following text is from Ezra Pound's 1909 poem \"Hymn III.\